name: Build and upload to PyPI

on: [push]
jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - os: macos-intel
            runs-on: macos-13
          - os: macos-arm
            runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.0
        env:
          CIBW_PLATFORM: ${{ matrix.platform || 'auto' }}

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ matrix.platform}}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
